# Generated by Django 5.0.4 on 2024-06-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0002_alter_contacto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'managed': False},
        ),
    ]
