# Generated by Django 5.0.4 on 2024-06-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0004_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
