# Generated by Django 5.0.4 on 2024-06-30 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0005_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='sesion_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopping_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pagado', 'Pagado'), ('No pagado', 'No pagado')], default='No pagado', max_length=45)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portafolio_app.cita')),
            ],
            options={
                'db_table': 'detalle_pago',
                'managed': True,
            },
        ),
    ]
