# Generated by Django 4.2.7 on 2024-05-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={},
        ),
    ]
