# Generated by Django 4.2.7 on 2024-05-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cliente_options_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='emails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.emails'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.telefono'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.comuna'),
        ),
        migrations.AddField(
            model_name='emails',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.persona'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='direccion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='telefono',
            table=None,
        ),
    ]
