# Generated by Django 5.0.4 on 2024-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='persona',
        ),
        migrations.DeleteModel(
            name='provincia',
        ),
        migrations.DeleteModel(
            name='region',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(blank='True', default=None, max_length=100, null='True', verbose_name='Apellido'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='contacto',
            name='destinatario',
            field=models.IntegerField(blank='True', choices=[(1, 'Juan Perez')], default=None, null='True', verbose_name='Tatuador'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank='True', default=None, max_length=254, null='True', verbose_name='Email'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null='True', verbose_name='Fecha de envio'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(blank='True', default=None, max_length=100, null='True', verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='direccion',
        ),
        migrations.DeleteModel(
            name='comuna',
        ),
        migrations.DeleteModel(
            name='emails',
        ),
        migrations.DeleteModel(
            name='telefono',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
